version: '3.8'

services:
  app:
    build: .
    container_name: sicra_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: sicra_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:    # senha que você colocou no .env
      MYSQL_DATABASE: sicra_db
      MYSQL_USER: ciuser               # usuário opcional para CI4
      MYSQL_PASSWORD: cipass           # senha opcional para CI4
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
